version: '3.9'

services:
  wordpress:
    image: wordpress:6.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    hostname: wp.dev
    ports:
      - 8086:80
    networks:
      - wp_network
    environment:
      WORDPRESS_DB_HOST: db.dev:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: random-password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppassword
    hostname: db.dev
    ports:
      - 5306:3306
    networks:
      - wp_network
    healthcheck:
      test: mariadb-admin -prandom-password ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: nginx.dev
    ports:
      - 8085:80
    networks:
      - wp_network
  pma:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.pma
    hostname: pma.dev
    ports:
      - 8087:80
    networks:
      - wp_network

volumes:
  wp_data:
  db_data:

networks:
  wp_network:
    driver: bridge